name: Update README activity

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  update-readme-with-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MSG: "chore: update README with recent activity"
          MAX_LINES: 10
